POST http://localhost:5500/api/v1/auth/sign-up
Content-Type: application/json

{
  "name": "Srujana",
  "email": "srujana@test.com",
  "password": "password123"
}


### Sign In
POST http://localhost:5500/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "srujana@test.com",
  "password": "password123"
}


### Get all users
GET http://localhost:5500/api/v1/users

### Get user by id
GET http://localhost:5500/api/v1/users/697517759a360ed14ef0acab

###fetch user
GET http://localhost:5500/api/v1/users/697517759a360ed14ef0acab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTc1MTc3NTlhMzYwZWQxNGVmMGFjYWIiLCJpYXQiOjE3NjkzMjQ4MTEsImV4cCI6MTc2OTQxMTIxMX0.heg2QRwFkDRG8G2JrU4BM8NycAGb0in1L1dwWIPXF5k
